name: Predictive Maintenance

on:
  workflow_dispatch:

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r Predictive-Maintenance/predictive-maintenance/requirements.txt

      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO: PratzPrathibha/predictive-maintenance-data
        run: python  Predictive-Maintenance/predictive-maintenance/model_building/data_register.py


  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r  Predictive-Maintenance/predictive-maintenance/requirements.txt

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO: PratzPrathibha/predictive-maintenance-data
        run: python predictive-maintenance/model_building/prep.py


  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r  Predictive-Maintenance/predictive-maintenance/requirements.txt

      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO: PratzPrathibha/predictive-maintenance-data
        run: python predictive-maintenance/model_building/train.py


  deploy-hosting:
    needs: [model-training, data-prep, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r  Predictive-Maintenance/predictive-maintenance/requirements.txt

      - name: Push files to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_REPO: PratzPrathibha/Predictive-maintenance
        run: python predictive-maintenance/hosting/hosting.py
